### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by smartmike** [HugoGiraudel/react-typeahead#1]
```
{ [Error: ENOENT: no such file or directory, open 'dist/index.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'dist/index.js' }
```

add a `dist/.gitkeep` file to avoid having to manually create the dist folder

**Comment by HugoGiraudel** [comment]
Done with: https://github.com/HugoGiraudel/react-typeahead/commit/1e444fc61701b769193ecd2f98915c934d2e5823.
